export enum RoutinesActionTypes {
  SET_CURRENT_ROUTINES = "SET_CURRENT_ROUTINES",
  ADD_ROUTINE = "ADD_ROUTINE",
  CHECK_ROUTINE = "CHECK_ROUTINE",
  REMOVE_ROUTINE = "REMOVE_ROUTINE",
  SKIP_ROUTINE = "SKIP_ROUTINE",
  CHANGE_ARCHIVE_OPTION = "CHANGE_ARCHIVE_OPTION",
  EDIT_ROUTINE = "EDIT_ROUTINE",
}
