export const popupActionTypes = {
  CHECK_POPUP: 'CHECK_POPUP',
  MESSAGE_POPUP: 'MESSAGE_POPUP',
  ADD_ROUTINE_POPUP: 'ADD_ROUTINE_POPUP',
  HIDE_POPUP: 'HIDE_POPUP',
  ADD_CATEGORY_POPUP: 'ADD_CATEGORY_POPUP',
};
